version: '3.5'

services:
  sanpetepantry:
    image: ${DOCKER_REGISTRY-}sanpetepantry/web:${BuildID}
    #ports:
     #- 80:80
    networks:
     pantrynet:
    restart: unless-stopped
    volumes:
     - ./data:/data

  reverseProxy:
    image: linuxserver/swag:latest
    environment:
     - TZ=America/Denver
     - URL=sanpetepantry.org
     #- SUBDOMAINS=beta
     - VALIDATION=http
     #- STAGING=true
    volumes:
     - ./default.conf:/config/nginx/site-confs/default:ro
     - cachedcerts:/config
    ports:
     - 443:443
     - 80:80
    restart: unless-stopped
    networks:
     pantrynet:

networks:
  pantrynet:

volumes: 
  cachedcerts: 