# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy.NET

on:
  push:
    branches: [ "beta" ]
  pull_request:
    branches: [ "beta" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "/home/github/actions-runner/dotnet"

    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: |
        cd scripts
        docker-compose -f docker-compose-beta.yml up --build -d
        docker images prune --quiet