name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: SFTP Deploy
      # You may pin to the exact commit or the version.
      # uses: wlixcc/SFTP-Deploy-Action@fe288f8e0f466f9567fb3e54434b41800cc7b880
      uses: wlixcc/SFTP-Deploy-Action@v1.0
      with:
        # username
        username: ${{secrets.GODADDY_USER}}
        # your sftp server
        server: ${{secrets.GODADDY_SERVER}}
        # your sftp server port, default to 22
        #port: # default is 22
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{secrets.GODADDY_PRIVATEKEY}}
        # will put all file under this path
        local_path: bin/Release/net5.0/publish
        # files will copy to under remote_path
        remote_path: /app
        # sftp args
        #args: # optional

