name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: sanpetepantry/web
        tag_with_sha: true
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2      
      with:
        file: SanpetePantry/Dockerfile
        push: true
        tags: ${{ steps.prepare.outputs.tag }}
        build-args: |
          exampleArg=exampleArgValue
          otherArg=$GITHUB_SHA
          
    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal    
    - name: Publish
      run: dotnet publish --configuration Release --self-contained true --runtime linux-x64 -p:PublishSingleFile=true

    - name: Stop the service
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:      
        #command: ps -aef | grep SanpetePantry | cut -d ' ' -f 2 | xargs kill
        command: kill $(ps aux | grep 'SanpetePantry' | awk '{print $2}')
        host: ${{ secrets.GODADDY_SERVER }}
        username: ${{ secrets.GODADDY_USER }}
        password:  ${{ secrets.GODADDY_PASSWORD }}

    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.GODADDY_SERVER }}
        username: ${{ secrets.GODADDY_USER }}
        password: ${{ secrets.GODADDY_PASSWORD }}
        localDir: SanpetePantry/bin/Release/net5.0/linux-x64/publish
        remoteDir: app

    - name: Start the service
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:      
        command: ./startWebsite
        host: ${{ secrets.GODADDY_SERVER }}
        username: ${{ secrets.GODADDY_USER }}
        password:  ${{ secrets.GODADDY_PASSWORD }}    

