name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: SFTP uploader
      # You may pin to the exact commit or the version.
      # uses: wangyucode/sftp-upload-action@24f8bb83383dc39bed201ee5da01475e6c38c568
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        # 
        host: ${{ secrets.GODADDY_SERVER }}
        # 
        #port: # optional, default is 22
        # 
        username: ${{ secrets.GODADDY_USER }}
        # 
        password: ${{ secrets.GODADDY_PASSWORD }}
        # 
        localDir: SanpetePantry/bin/Release/net5.0
        # 
        remoteDir: app
        # 
        #dryRun: # optional

    

